# Generated by Django 5.1.3 on 2024-12-02 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('timezone_offset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDetails3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_dt', models.DateTimeField()),
                ('daily_sunrise', models.DateTimeField()),
                ('daily_sunset', models.DateTimeField()),
                ('daily_moonrise', models.DateTimeField()),
                ('daily_moonset', models.DateTimeField()),
                ('daily_temp_day', models.IntegerField()),
                ('daily_temp_min', models.IntegerField()),
                ('daily_temp_max', models.IntegerField()),
                ('daily_feels_like_day', models.FloatField()),
                ('daily_feels_like_night', models.FloatField()),
                ('daily_pressure', models.IntegerField()),
                ('daily_humidity', models.IntegerField()),
                ('daily_dew_point', models.FloatField()),
                ('daily_wind_speed', models.FloatField()),
                ('daily_wind_deg', models.IntegerField()),
                ('daily_wind_gust', models.IntegerField()),
                ('daily_id', models.IntegerField()),
                ('daily_main', models.CharField(max_length=30)),
                ('daily_description', models.CharField(max_length=30)),
                ('daily_icon', models.CharField(max_length=30)),
                ('daily_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailykey', to='weather.weatherkey')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDetails2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_dt', models.DateTimeField()),
                ('hourly_temp', models.IntegerField()),
                ('hourly_feels_like', models.FloatField()),
                ('hourly_pressure', models.IntegerField()),
                ('hourly_humidity', models.IntegerField()),
                ('hourly_dew_point', models.FloatField()),
                ('hourly_clouds', models.IntegerField()),
                ('hourly_visibility', models.IntegerField()),
                ('hourly_wind_speed', models.FloatField()),
                ('hourly_wind_deg', models.IntegerField()),
                ('hourly_wind_gust', models.IntegerField()),
                ('hourly_id', models.IntegerField()),
                ('hourly_main', models.CharField(max_length=30)),
                ('hourly_description', models.CharField(max_length=30)),
                ('hourly_icon', models.CharField(max_length=30)),
                ('hourly_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourlykey', to='weather.weatherkey')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_dt', models.DateTimeField()),
                ('current_sunrise', models.DateTimeField()),
                ('current_sunset', models.DateTimeField()),
                ('current_temp', models.IntegerField()),
                ('current_feels_like', models.FloatField(null=True)),
                ('current_pressure', models.IntegerField()),
                ('current_humidity', models.IntegerField()),
                ('current_dew_point', models.FloatField()),
                ('current_clouds', models.IntegerField()),
                ('current_visibility', models.IntegerField()),
                ('current_wind_speed', models.FloatField()),
                ('current_wind_deg', models.IntegerField()),
                ('current_id', models.IntegerField()),
                ('current_main', models.CharField(max_length=30)),
                ('current_description', models.CharField(max_length=30)),
                ('current_icon', models.CharField(max_length=30)),
                ('current_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curentkey', to='weather.weatherkey')),
            ],
        ),
    ]
